---
title: "figure mono"
author: "Johannes Titz"
date: "12/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(gridExtra)
library(tidyverse)

latent_var <- c(1, 2, 2.5, 3, 4, 5)
d1 <- data.frame(plot = 1, x = latent_var, y = c(1, 2, 2, 4, 5, 5))
d2 <- data.frame(plot = 2, x = latent_var, y = c(1, 1, 2, 3, 5, 5))
d3 <- data.frame(plot = 3, x = d1$y, y = d2$y)
d <- rbind(d1, d2, d3)

fdrtool::monoreg(d3$x, d3$y)

p1 <- ggplot(d1, aes(y, x)) + geom_point() + theme_bw() +  coord_fixed() +
  theme_classic() + 
  scale_x_continuous(name = "Item 1", limits = c(1, 5), breaks = 1:5) +
  scale_y_continuous(name = "Latent Variable", limits = c(1, 5), breaks = latent_var,
                     labels = c(letters[1:6]))

p2 <- ggplot(d2, aes(x, y)) + geom_point() + theme_bw() + coord_fixed() + 
  theme_classic() +
  scale_y_continuous(name = "Item 2", limits = c(1, 5), breaks = 1:5) +
  scale_x_continuous(name = "Latent Variable", limits = c(1, 5), breaks = latent_var,
                     labels = c(letters[1:6]))

p3 <- ggplot(d3, aes(x, y, label = c(letters[1:4], "e,f", ""))) + geom_point() + theme_bw() + coord_fixed() + 
  theme_classic() +
  scale_y_continuous("Item 2", limits = c(1, 5), breaks = 1:5) + 
  scale_x_continuous("Item 1", limits = c(1, 5), breaks = 1:5) + 
  geom_text(hjust = c(-1, -1, -1, -1, 1.5, 0))

p4 <- ggplot() + theme_void() #+ 
  # annotate("text", x = 1, y = 1, label = paste(
  #   "If there is a monotonic relationship between a latent variable and two items",
  #   "(subfigures A and B) then both items are also monotonically related (subfigure C)."
  #   )
  # )
#grid.arrange(p2, p3, p4, p1)
library(cowplot)
plot_grid(p2, p3, p4, p1, labels = c("A", "C", "", "B"))
```

```{r}
pdf("plots/monofig.pdf", width = 6, height = 6)
#grid.arrange(p2, p3, p4, p1)
plot_grid(p2, p3, p4, p1, labels = c("A", "C", "", "B"))
dev.off()
```

